//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public int Id { get; set; }
        public string AlbumID { get; set; }
        public string AlbumName { get; set; }
        public Nullable<int> AlbumReleaseDate { get; set; }
        public Nullable<double> AlbumRating { get; set; }
        public int ArtistId { get; set; }
    
        public virtual Artist Artist { get; set; }
    }
}
